version: 2
updates:
   -  package-ecosystem: "mix"
      directory: "/"
      schedule:
         interval: "daily"
   -  package-ecosystem: "npm"
      directory: "/"
      schedule:
         interval: "daily"
